DO $$ BEGIN
  CREATE TYPE user_tipo AS ENUM ('EI', 'CLIENTE_PREFERENCIAL', 'ADMIN');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE kit_tipo AS ENUM ('STANDARD', 'PREMIUM');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE pedido_tipo AS ENUM ('KIT_INICIAL', 'UPGRADE', 'RECOMPRA');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE pedido_status AS ENUM ('PENDENTE', 'PAGO', 'CANCELADO', 'ESTORNADO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE graduacao AS ENUM (
    'NENHUMA', 'BRONZE', 'PRATA', 'OURO', 'SAFIRA', 'ESMERALDA',
    'DIAMANTE', 'DUPLO_DIAMANTE', 'TRIPLO_DIAMANTE', 'IMPERIAL',
    'EMBAIXADOR', 'EMBAIXADOR_GLOBAL'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE bonus_tipo AS ENUM ('PRIMEIRO_PEDIDO', 'UPGRADE', 'PRODUTIVIDADE', 'EQUIPARACAO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE ciclo_status AS ENUM ('ABERTO', 'PROCESSANDO', 'FECHADO', 'ERRO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lancamento_status AS ENUM ('PROVISIONADO', 'LIBERADO', 'PAGO', 'ESTORNADO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE doc_status AS ENUM ('PENDENTE', 'APROVADO', 'REJEITADO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE saque_status AS ENUM ('SOLICITADO', 'APROVADO', 'PAGO', 'REJEITADO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
